site_name: ZippyGigs | Documentation
pages:
- Home: 'index.md'
- Reference:
   - 'Authorization': 'reference/authorization.md'
   - 'Vendors': 'reference/vendors.md'
   - 'Client': 'reference/client.md'
   - 'Order': 'reference/order.md'
   - 'Gig': 'reference/gig.md'


